[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/group"
  to = "/group.html"
  status = 200

[[redirects]]
  from = "/g/:slug"
  to = "/group.html?id=:slug"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
